version: '2'
services:
 da1:
  image: cc/private-tor
  #expose:
  #  - "7000"
  #  - "9030"
  environment:
    ROLE: DA
  volumes:
    ## Needed to keep track of other nodes
    - ./tor:/tor
  container_name: da1
 da2:
  image: cc/private-tor
  #expose:
  #  - "7000"
  #  - "9030"
  environment:
    ROLE: DA
  volumes:
    ## Needed to keep track of other nodes
    - ./tor:/tor
  container_name: da2
 da3:
  image: cc/private-tor
  #expose:
  #  - "7000"
  #  - "9030"
  environment:
    ROLE: DA
  volumes:
    ## Needed to keep track of other nodes
    - ./tor:/tor
  container_name: da3
 relay:
  image: cc/private-tor
  #expose:
  #  - "7000"
  #  - "9030"
  environment:
    ROLE: RELAY
  volumes:
    - ./tor:/tor
  depends_on:
    # Make sure the DA's are already up
    - da1
    - da2
    - da3
  # container_name: relay
 exit:
  image: cc/private-tor
  #expose:
  #  - "7000"
  #  - "9030"
  environment:
    ROLE: EXIT
  volumes:
    - ./tor:/tor
  depends_on:
    # Make sure the DA's are already up
    - da1
    - da2
    - da3
  # container_name: exit
 client:
  image: cc/private-tor
  ports:
    # Setups a listener on host machine
    - "9050:9050"
    - "9051:9051"
    - "5000:5000"
    - "80:80"
  volumes:
    - ./tor:/tor
  environment:
    ROLE: CLIENT
  depends_on: 
    - da1
    - da2
    - da3
  # container_name: client
 hs:
  image: cc/private-tor
  #expose:
  #  - "80"
  environment:
    ROLE: HS
    # This will create a hidden service that points to
    # the service "web" which is runing nginx. You can 
    # change this to whatever ip or hostname you want
    TOR_HS_PORT: "80"
    TOR_HS_ADDR: "web"
  volumes:
    - ./tor:/tor
  depends_on:
    - da1
    - da2
    - da3
  links:
    - web
  # container_name: hs
 web:
  image: nginx
  #expose:
  #  - "80"
  # container_name: web
 dps:
  image: defreitas/dns-proxy-server
  hostname: dns.mageddo
  volumes:
    - /etc/resolv.conf:/etc/resolv.conf
    - /var/run/docker.sock:/var/run/docker.sock

